import argparse
import json
import os
from database import init_db, get_session
from models import Collaborator, Work, WorkAuthor, Collaboration

FLASK_DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'app', 'main', 'static', 'data')

def do_init():
    if os.path.exists(os.path.join(os.path.dirname(__file__), 'research_network.db')):
        os.remove(os.path.join(os.path.dirname(__file__), 'research_network.db'))
    init_db()

def do_import():
    session = get_session()
    
    me = session.query(Collaborator).filter_by(is_self=True).first()
    if not me:
        me = Collaborator(
            is_self=True,
            full_name="Indrajit Ghosh",
            nickname="me",
            email="indrajitg@iitk.ac.in",
            institution="Indian Institute of Technology Kanpur",
            department="Department of Mathematics",
            position="Institute Postdoctoral Fellow",
            website="https://sites.google.com/view/exploring-infinity-within",
            orcid="0009-0007-6353-6637"
        )
        session.add(me)

    collabs_data = [
        {"nickname": "snayak", "full_name": "Soumyashant Nayak", "institution": "Indian Statistical Institute, Bangalore", "website": "https://www.isibang.ac.in/~soumyashant/"},
        {"nickname": "kkmukherjee", "full_name": "Kunal Krishna Mukherjee", "institution": "IIT Madras", "website": "https://ioe.iitm.ac.in/people/kunal-krishna-mukherjee/"},
        {"nickname": "kcbakshi", "full_name": "Keshab Chandra Bakshi", "institution": "IIT Kanpur", "website": "https://sites.google.com/view/keshab-bakshi/home"},
        {"nickname": "skumar", "full_name": "Sumit Kumar"},
        {"nickname": "gmaiti", "full_name": "Gahin Maiti"},
        {"nickname": "vpgupta", "full_name": "Ved Prakash Gupta", "website": "https://sites.google.com/view/ved-prakash-gupta"}
    ]

    collab_map = {'me': me}

    for c_data in collabs_data:
        c = session.query(Collaborator).filter_by(nickname=c_data['nickname']).first()
        if not c:
            c = Collaborator(**c_data)
            session.add(c)
        collab_map[c_data['nickname']] = c
    
    session.commit()

    relationships = [
        ('me', 'snayak', 'established'),
        ('me', 'kkmukherjee', 'established'),
        ('me', 'kcbakshi', 'established'),
        ('me', 'skumar', 'ongoing'),
        ('me', 'gmaiti', 'ongoing'),
        ('me', 'vpgupta', 'ongoing'),
        ('snayak', 'kcbakshi', 'established'),
        ('snayak', 'gmaiti', 'ongoing'),
        ('vpgupta', 'skumar', 'established'),
        ('vpgupta', 'kcbakshi', 'established')
    ]

    for id1, id2, status in relationships:
        c1 = collab_map.get(id1)
        c2 = collab_map.get(id2)
        if c1 and c2:
            c1.add_collaboration(session, c2, status=status)

    session.commit()

    works_data = [
        {
            "title": "Algebraic aspects and functoriality of the set of affiliated operators",
            "authors": ["me", "snayak"],
            "work_type": "publication",
            "status": "published",
            "journal_conference": "International Mathematics Research Notices",
            "volume": "2024",
            "issue": "21",
            "pages": "13525-13562",
            "publication_date": "Nov 2024",
            "year": 2024,
            "doi": "10.1093/imrn/rnae203",
            "arxiv_id": "2311.16170",
            "researchgate_url": "https://www.researchgate.net/publication/383623934_Algebraic_aspects_and_functoriality_of_the_set_of_affiliated_operators",
            "abstract": "In this article, we aim to provide a satisfactory algebraic description of the set of affiliated operators for von Neumann algebras. Let \\(\\mathscr{M}\\) be a von Neumann algebra acting on a Hilbert space \\(\\mathcal{H}\\), and let \\(\\mathscr{M}_{\\text{aff}}\\) denote the set of unbounded operators of the form \\(T = AB^{\\dagger}\\) for \\(A, B \\in \\mathscr{M}\\) with \\(\\text{null} (B) \\subseteq \\text{null} (A)\\), where \\((\\cdot)^{\\dagger}\\) denotes the Kaufman inverse. We show that \\(\\mathscr{M}_{\\text{aff}}\\) is closed under sum, product, Kaufman-inverse and adjoint, and has the structure of a <i>(right) near-semiring</i>; Moreover, the above quotient representation of an operator in \\(\\mathscr{M}_{\\text{aff}}\\) is essentially unique. Thus we may view \\(\\mathscr{M}_{\\text{aff}}\\) as the multiplicative monoid of unbounded operators on \\(\\mathcal{H}\\) generated by \\(\\mathscr{M}\\) and \\(\\mathscr{M} ^{\\dagger}\\). We further show that our definition of affiliation, as reflected in \\(\\mathscr{M}_{\\text{aff}}\\), subsumes the traditional one. Let \\(\\Phi\\) be a unital normal \\(*\\)-homomorphism between represented von Neumann algebras \\((\\mathscr{M}; \\mathcal{H})\\) and \\((\\mathscr{N}; \\mathcal{K})\\). Using the quotient representation, we obtain a canonical extension of \\(\\Phi\\) to a mapping \\(\\Phi_{\\text{aff}} : \\mathscr{M}_{\\text{aff}} \\to \\mathscr{N}_{\\text{aff}}\\) which is a near-semiring homomorphism that respects Kaufman-inverse and adjoint; in addition, \\(\\Phi_{\\text{aff}}\\) respects Murray-von Neumann affiliation of operators and also respects strong-sum and strong-product. Thus \\(\\mathscr{M}_{\\text{aff}}\\) is intrinsically associated with \\(\\mathscr{M}\\) and transforms functorially as we change representations of \\(\\mathscr{M}\\). Furthermore, \\(\\Phi_{\\text{aff}}\\) preserves operator properties such as being symmetric, or positive, or accretive, or sectorial, or self-adjoint, or normal, and also preserves the Friedrichs and Krein-von Neumann extensions of densely-defined closed positive operators. As a proof of concept, we transfer some well-known results about closed unbounded operators to the setting of closed affiliated operators for properly infinite von Neumann algebras, via 'abstract nonsense'."
        },
        {
            "title": "An Operator Theoretic Characterization of Properly Infinite von Neumann Algebras",
            "authors": ["me", "kkmukherjee"],
            "work_type": "preprint",
            "status": "preprint",
            "publication_date": "Feb 2026",
            "year": 2026,
            "abstract": ""
        },
        {
            "title": "A Complete Characterization of Regular Inclusions of Finite Dimensional \\(C^*\\)-algebras",
            "authors": ["kcbakshi", "me", "skumar"],
            "work_type": "preprint",
            "status": "preprint",
            "publication_date": "Aug 2026",
            "year": 2026,
            "arxiv_id": "2608.04572",
            "researchgate_url": "https://www.researchgate.net/publication/411714884_A_Complete_Characterization_of_Regular_Inclusions_of_Finite_Dimensional_C-algebras",
            "abstract": "We give a complete characterization of regular (in the sense of Kumjian and Renault) unital inclusions of finite-dimensional \\(C^*\\)-algebras. For subalgebras \\(\\bigoplus_j( \\mathbb{M}_{d_j}(\\mathbb{C}) \\otimes \\mathbb{I}_{p_j})\\) of \\(\\mathbb{M}_n(\\mathbb{C})\\), we show that regularity depends only on equality of the multiplicities \\(p_j\\), while unitary regularity—characterized recently by the first author and Silambarasan—additionally requires equality of the \\(d_j\\); we recover the latter via a streamlined alternative proof. Extending this to inclusions of arbitrary finite-dimensional \\(C^*\\)-algebras, encoded by an inclusion matrix \\(\\Lambda\\), we show that regularity is equivalent to an explicit row/column condition on \\(\\Lambda\\)—coinciding with the normalizer matrix introduced by the first author and Silambarasan—so that the device used there to detect unitary regularity is shown to characterize regularity in general; unitary regularity is recovered by a further dimension-equality condition."
        },
        {
            "title": "A Complete Characterization of Cartan Inclusions of Finite Dimensional \\(C^*\\)-algebras",
            "authors": ["me", "skumar"],
            "work_type": "preprint",
            "status": "preprint",
            "publication_date": "Aug 2026",
            "year": 2026,
            "arxiv_id": "2608.11711",
            "researchgate_url": "https://www.researchgate.net/publication/412212199_A_Complete_Characterization_of_Cartan_Inclusions_of_Finite_Dimensional_C-algebras",
            "abstract": "We give a complete characterization of Cartan inclusions of finite dimensional \\(C^*\\)-algebras in terms of their inclusion matrices. More precisely, for a unital inclusion \\(\\mathcal{B}\\subseteq\\mathcal{A}\\) with inclusion matrix \\(\\Lambda=(\\Lambda_{ij})\\), where Cartan means that \\(\\mathcal{B}\\) is a generalized Cartan subalgebra of \\(\\mathcal{A}\\) in the sense of Exel, we prove that the inclusion is Cartan if and only if\n                \\[ \\sum_i \\Lambda_{ij}\\leq 1 \\]\n                for every \\(j\\). We call matrices satisfying this condition multiplicity free. Thus, our characterization provides a purely combinatorial criterion for determining when a finite dimensional inclusion is Cartan. We further prove that every Cartan inclusion admits a unique conditional expectation from \\(\\mathcal{A}\\) onto \\(\\mathcal{B}\\). Conversely, we show that, for unital inclusions of finite dimensional \\(C^*\\)-algebras, the uniqueness of the conditional expectation is sufficient for the inclusion to be Cartan. Consequently, a unital inclusion \\(\\mathcal{B}\\subseteq\\mathcal{A}\\) of finite dimensional \\(C^*\\)-algebras is Cartan if and only if there exists a unique conditional expectation from \\(\\mathcal{A}\\) onto \\(\\mathcal{B}\\)."
        },
        {
            "title": "Regularity for Subfactors",
            "authors": ["kcbakshi", "me"],
            "work_type": "preprint",
            "status": "preprint",
            "publication_date": "Sep 2026",
            "year": 2026,
            "arxiv_id": "2609.10118",
            "abstract": "\nWe study three naturally associated notions of regularity for a unital inclusion of von Neumann algebras \\(\\mathcal{B} \\subseteq \\mathcal{M}\\): regularity, groupoid regularity, and unitary regularity. We first observe that regularity and groupoid regularity are unconditionally equivalent by showing that the standard normaliser and the groupoid normaliser of \\(\\mathcal{B}\\) in \\(\\mathcal M\\) generate the same linear span. The central question addressed in this work is whether regularity implies unitary regularity. For arbitrary von Neumann subalgebras, we demonstrate that this implication fails dramatically; we construct explicit examples to show that every factor (of type \\(\\mathrm{I}_\\infty\\), \\(\\mathrm{II}_1\\), \\(\\mathrm{II}_\\infty\\), and \\(\\mathrm{III}\\)) contains a regular von Neumann subalgebra that is not unitarily regular. In stark contrast, we prove that the behaviour changes completely in the setting of subfactors. For subfactor inclusions across all these types, regularity always implies unitary regularity, and thus all three notions of regularity coincide. Finally, we establish an analogous result for irreducible unital inclusions of simple \\(C^*\\)-algebras admitting a conditional expectation of finite Watatani index. In this setting, we prove that regularity, unitary regularity, being a generalised Cartan subalgebra, and arising from a crossed product by a finite group are all mutually equivalent conditions."
        },
        {
            "title": "Kadison-Kastler Distance and Interior Angle for Masas: Connections with Entropy and Probabilistic Index",
            "authors": ["me", "skumar"],
            "work_type": "preprint",
            "status": "preprint",
            "publication_date": "",
            "year": 2026,
            "abstract": "We study the Kadison--Kastler distance and the interior angle between masas in finite-dimensional matrix algebras. In \\(\\mathbb{M}_2(\\mathbb{C})\\), we obtain an explicit formula for the Kadison--Kastler distance between two masas and show that every value in \\([0,1]\\) occurs as \\(\\mathrm{d}_{\\textrm{KK}}(\\Delta,u\\Delta u^*)\\). Moreover, the distance attains its maximal value precisely when the relative unitary is a Hadamard unitary. We further establish the identity\n                \\[ \\mathrm{d}_{\\textrm{KK}}(u\\Delta u^*,v\\Delta v^*)=\\sin\\alpha(u\\Delta u^*,v\\Delta v^*) \\]\n                and show that the Kadison--Kastler distance between \\(\\Delta\\) and \\(v\\Delta v^*\\) takes only its minimal or maximal value when \\(v\\) belongs to the groupoid normaliser of \\(\\Delta\\). Most notably, in \\(\\mathbb{M}_2(\\mathbb{C})\\) we establish the equivalence, for any unitaries \\(u,v\\), of maximal Kadison--Kastler distance, maximal interior angle, maximal Connes--Stormer modified entropy, and minimal Popa probabilistic index; namely,\n                \\[ \\mathrm{d}_{\\mathrm{KK}}(u\\Delta u^*,v\\Delta v^*)=1 \\iff h(u\\Delta u^*,v\\Delta v^*)=\\log 2 \\iff \\alpha(u\\Delta u^*,v\\Delta v^*)=\\frac{\\pi}{2} \\iff \\lambda(u\\Delta u^*,v\\Delta v^*)=\\frac12. \\]\n                For general \\(\\mathbb{M}_n(\\mathbb{C})\\), we prove a unitary invariance property for the interior angle and derive an explicit formula for the angle between arbitrary masas of the form \\(u\\Delta^{(n)}u^*\\) and \\(v\\Delta^{(n)}v^*\\). As a consequence, the interior angle is \\(\\frac{\\pi}{2}\\) precisely when \\(u^*v\\) is a Hadamard unitary. Finally, we show that every value in \\(\\left[ 0,\\frac{\\pi}{2} \\right]\\) occurs as the interior angle between a pair of masas in \\(\\mathbb{M}_n(\\mathbb{C})\\)."
        },
        {
            "title": "A Royal Road to the Basic Theory of Unbounded Operators on Hilbert Space",
            "authors": ["me", "snayak", "gmaiti"],
            "work_type": "ongoing",
            "status": "ongoing"
        },
        {
            "title": "On Kadison-Kastler Distance",
            "authors": ["me", "skumar"],
            "work_type": "ongoing",
            "status": "ongoing"
        },
        {
            "title": "On Connes-Størmer Entropy",
            "authors": ["kcbakshi", "me", "snayak"],
            "work_type": "ongoing",
            "status": "ongoing"
        },
        {
            "title": "On Interior Angle Between Intermediate Subalgebras",
            "authors": ["kcbakshi", "me", "vpgupta"],
            "work_type": "ongoing",
            "status": "ongoing"
        }
    ]

    for w_data in works_data:
        w = None
        if "arxiv_id" in w_data and w_data["arxiv_id"]:
            w = session.query(Work).filter_by(arxiv_id=w_data["arxiv_id"]).first()
        if not w:
            w = session.query(Work).filter_by(title=w_data["title"]).first()

        if not w:
            kwargs = {k: v for k, v in w_data.items() if k != "authors"}
            w = Work(**kwargs)
            session.add(w)
            session.flush()

            for order, nickname in enumerate(w_data["authors"], start=1):
                collab = collab_map.get(nickname)
                if collab:
                    wa = WorkAuthor(work_id=w.id, collaborator_id=collab.id, author_order=order)
                    session.add(wa)

    session.commit()
    print("Database seeded successfully with existing research data!")

def compute_distances(session):
    me = session.query(Collaborator).filter_by(is_self=True).first()
    if not me: return {}

    distances = {me.id: 0}
    queue = [me.id]
    
    while queue:
        current_id = queue.pop(0)
        c = session.get(Collaborator, current_id)
        for neighbor, _ in c.get_collaborators():
            if neighbor.id not in distances:
                distances[neighbor.id] = distances[current_id] + 1
                queue.append(neighbor.id)
                
    return distances

def get_short_name(full_name):
    parts = full_name.split()
    if len(parts) <= 1:
        return full_name
    initials = " ".join([p[0].upper() + "." for p in parts[:-1]])
    return f"{initials} {parts[-1]}"

def do_export():
    session = get_session()
    os.makedirs(FLASK_DATA_DIR, exist_ok=True)
    
    distances = compute_distances(session)

    collaborators_export = []
    for c in session.query(Collaborator).all():
        established = []
        ongoing = []
        for neighbor, status in c.get_collaborators():
            if status == "ongoing":
                ongoing.append(neighbor.nickname or neighbor.id)
            else:
                established.append(neighbor.nickname or neighbor.id)
        
        
        collaborator_dict = {
            "id": c.nickname,
            "uuid": c.id,
            "name": c.full_name,
            "email": c.email or "",
            "website": c.website or "",
            "institution": c.institution or "",
            "department": c.department or "",
            "position": c.position or "",
            "affiliation": c.affiliation or "",
            "orcid": c.orcid or "",
            "bio": c.bio or "",
            "distance": distances.get(c.id, -1),
            "is_me": c.is_self,
            "connections": established,
            "ongoing_connections": ongoing
        }
        collaborators_export.append(collaborator_dict)

    collab_path = os.path.join(FLASK_DATA_DIR, 'collaborators.json')
    with open(collab_path, 'w', encoding='utf-8') as f:
        json.dump(collaborators_export, f, indent=2)
    print(f"Exported {len(collaborators_export)} collaborators to {collab_path}")

    # Sort so that display_order > 0 comes first (ascending).
    # display_order == 0 comes last (at the bottom of the JSON).
    works_query = session.query(Work).all()
    works_query.sort(key=lambda w: (1 if w.display_order == 0 else 0, w.display_order))
    works = works_query
    
    grouped_works = {
        "publications": [],
        "preprints": [],
        "ongoing": []
    }
    
    for w in works:
        authors = []
        # Sort authors by last name
        sorted_was = sorted(w.authors, key=lambda wa: wa.collaborator.full_name.split()[-1].lower())
        for wa in sorted_was:
            authors.append({
                "name": get_short_name(wa.collaborator.full_name),
                "is_me": wa.collaborator.is_self,
                "order": wa.author_order  # kept for legacy/debugging but list is naturally sorted
            })
            
        work_dict = {
            "id": w.id,
            "title": w.title,
            "subtitle": w.subtitle,
            "abstract": w.abstract,
            "year": w.year,
            "display_order": w.display_order,
            "publication_date": w.publication_date,
            "journal_conference": w.journal_conference,
            "volume": w.volume,
            "issue": w.issue,
            "pages": w.pages,
            "doi": w.doi,
            "arxiv_id": w.arxiv_id,
            "researchgate_url": w.researchgate_url,
            "authors": authors
        }
        
        if w.work_type == "publication":
            grouped_works["publications"].append(work_dict)
        elif w.work_type == "preprint":
            grouped_works["preprints"].append(work_dict)
        elif w.work_type == "ongoing":
            grouped_works["ongoing"].append(work_dict)

    for group, items in grouped_works.items():
        path = os.path.join(FLASK_DATA_DIR, f'{group}.json')
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(items, f, indent=2)
        print(f"Exported {len(items)} {group} to {path}")

def do_validate():
    session = get_session()
    me = session.query(Collaborator).filter_by(is_self=True).all()
    if len(me) != 1:
        print(f"[FAIL] Found {len(me)} 'self' records. Expected exactly 1.")
    else:
        print("[PASS] Exactly one 'self' researcher found.")
        
    works = session.query(Work).all()
    orphan_works = [w for w in works if not w.authors]
    if orphan_works:
        print(f"[WARN] Found {len(orphan_works)} works with no authors.")
    else:
        print("[PASS] All works have assigned authors.")
        
    print("Validation complete.")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Local Data Manager for Research Network")
    parser.add_argument('command', choices=['init', 'import', 'export', 'validate'])
    args = parser.parse_args()

    if args.command == 'init':
        do_init()
    elif args.command == 'import':
        do_import()
    elif args.command == 'export':
        do_export()
    elif args.command == 'validate':
        do_validate()
